### ISSUE TITLE
[Feature Request] Allow enchanting of Runic Armor

### ISSUE THREAD

**Issue by duhadventure** [KryptonCaptain/Thaumic-Dyes#9]
The current state of Runic armor in comparison to other late game armors is a bit underwhelming. After taking down the shield, even with upgrades, a diamond sword can make short work of the user, even with full charge. Considering when you get up to Tier 3, using 4 Primordial Pearls to achieve a full set, losing all your runic leaves you extremely vulnerable.

Me and a friend tested runic armor with Hardened and Shield Nexus upgrades, and when compared to armors like Thaumium Fortress (TC4), Void Fortress (TM) or other armors like Terrasteel, it felt weak in comparison. Allowing it to be enchanted, or adding a config something like this would be appreciated:

canrunicbemagic = true (enables runic armor to be enchanted)

**Comment by 63502** [comment]
The main feature of runic armor is that it is made of enchantments. The reason that it cannot be enchanted even at the armor's highest level is because magic cannot be applied to magic.

That being said, I do agree with the point you make about the abyssal armor not being as strong as it probably should be. For the amount of effort it takes to craft, it is a bit underpowered, even with upgrades.

I have a few more practical suggestions as to how to fix this.

- Make an augment that causes the wearer to progressively take less damage per hit if attacked or damaged continuously while shields are up.

- Make an augment that significantly decreases the amount of total damage the wearer takes overall while shields are up. Something like 50-80% less.

- Make an augment or bauble that gives the wearer exponentially greater shield recharge speed when the wielder has a full set of runic armor on. Maybe a Runic Girdle of Recharge?

- Make an augment or bauble that regenerates 50-75% of damage taken to shields after the wearer has not sustained damage for at least 5 seconds

- Make an(expensive) augment that decreases all incoming damage by 1/2 a heart per armor piece with the upgrade(can only be applied once per piece, regardless of the set worn). This would mean that with a full set with this augment, all incoming damage is reduced by 4, or 2 hearts. When shields go down, the damage reduction is lost, but the wearer gains a 75% chance to survive fatal damage as long as they are at or above 4 hearts of health. (Goliath augment?)

**Comment by KryptonCaptain** [comment]
Hardened was a funny thing when I was working on the Tier 3 set. Those experiments are the reason you can only apply 2 levels of it - because how I had it with the damage reduction calcs, 3 levels of Hardened made you completely damage immune.
I definitely will look at buffing the base protection value of the T3 set though, to at least be on par with the void robes (19-20 armour) used to craft it (and maybe T2 to iron tier).
Might be a rework on Hardened too, since I'll have to adjust it for each set if they have different protection values. Also because it does the ?displayArmor thing, and if the DR exceeds ~24 armour, it makes you invincible.

---------

While I'd love to do augments that alter charge time, I can't. Simply because half the code I need are private functions that I can't access. I'm sure Azanor had his reasons for that.
And since I can't into advanced java _yet_, that's not changing in the near future either.

Adding DR while shields are up might be possible, but I'm not sure yet, because of how the events are handled.

**Comment by WyvernArchmage** [comment]
So basically, with the augments that exist now, if you could make it so they can be anvil enchanted like armor normally can be, it's pretty balanced along with the other options available. Also, you should put something in the book about only 2 levels of hardness counting. If it isn't possible right now to add 3 normally but it would theoretically work, well, we NBT edited on the 3 layers of hardened per armor piece (faster to test) and even 3x Hardened set with prot V you are nowhere near invincible...

And to ease your mind on the lore side 63502, it -does- have a physical set of void robes infused into it. I'm only saying making the tier 3 enchantable.

**Comment by Dayyer1** [comment]
I find it odd that teir 3 has the same protection levels as teir 1, especially considering the recipe for teir 3. I do see how that would affect Hardening, though.

**Comment by Dayyer1** [comment]
Whoops, just re-read KC's comment...

**Comment by KryptonCaptain** [comment]
@WyvernArchmage 
I'll change the page for Hardened shortly.
Also, even if you gave a piece of armour 3x Hardened via infusion, NBT or /give, it won't do shit, because the code only counts 2 levels of it anyway.

Making T3 enchantable isn't entirely unreasonable, but it looks **really** stupid having the enchant VFX on the set's special visual effect (which I assume everyone here has discovered by now). So it's a tough call, considering the focus of the mod is more or less "sweet aesthetics first, function second"

**Comment by 63502** [comment]
@WyvernArchmage Technically, the whole set is originally inscribed on a set of gold armor, but I see where you are going with this. Your explanation could actually make quite a lot of sense lore-wise if you pair it with the reality/magic bending properties of 4 primordial pearls.

**Comment by duhadventure** [comment]
@KryptonCaptain can you hide enchantment effect?

**Comment by 63502** [comment]
I've seen it done in 1.7.10 before. How it was done and whether or not it was intentional, I don't know.

**Comment by KryptonCaptain** [comment]
You can disable enchant glint with a resource pack, which I occasionally do, but I'm not aware of a way to do it with code

**Comment by duhadventure** [comment]
@KryptonCaptain found this

"In 1.7.10, the armour renderer uses ItemStack#isItemEnchanted to determine whether to render the enchantment glint.

In 1.10.2, the armour renderer uses ItemStack#hasEffect (which uses Item#hasEffect) to determine whether to render the enchantment glint.

The only way to fix this is to stop using 1.7.10 (which is no longer supported by Forge) and update to 1.10.2."

Not sure what they mean by this. Not a coder. Either means you can do in both versions or only 1.10

**Comment by Dayyer1** [comment]
Hm... Tier 3 protection: Hardened vs. void robes...
Having a fully Hardened (or, full armor bar's worth) set of armor on tier 3 runic armor takes up about half of your augment space, and it is also odd when you think that you've added void robes to a set of armor. (I know you've thought of that--just reviewing)
Although, if you had void robe-level protection on the runic armor and then added Hardened... well, you can imagine the outcome.
So, what about doing something like bumping up T2 by 1 armor point on each piece, and then on T3, bump it up another armor point? Then, you've still got better protection, but room for Hardened (maybe).

Or make some sort of lore that says that Hardened isn't very effective on T3.

T3 does seem a bit underpowered if you have to add hardened to it, considering you're using 4 pearls for 6 or 7 armor points total, and also being unenchantable.

Btw, I think the latest update is a really cool addition, one I wasn't expecting. :)

**Comment by KryptonCaptain** [comment]
![image](https://user-images.githubusercontent.com/8790829/28302045-67235d86-6bce-11e7-8a06-1ed481bf1ce4.png)

T3 armour now matches void tier as expected. T2 is iron tier. T1 is unchanged.
Hardened is under review for how it will behave, and could be restricted to 1 slot functionality. Will remain the same for T1, doubling the protection value. T2 might add 1 armour point instead if I can figure out the math for it - bringing it to 19 armour with 4 augs. T3 is uncertain - if there was a place to allow enchanting, this might be it, saying lore-wise that enough mass has coalesced around the robes to make it possible, but I also don't want to give too much about the T3 robes away to new players. Which leads into the issue of undocumented features, like the secondary shield breach effects if you have 4 or more of the same (breach) augment. Also that code tests so far only allow enchanting T3 via anvil for some reason

**Comment by Dayyer1** [comment]
Auto-repair augment. (You already seem to have enough to do, though. Don't mind me.)

**Comment by Dayyer1** [comment]
What do you mean, secondary shield breach effects?

**Comment by KryptonCaptain** [comment]
I mean the [super undocumented secondary breach effects](https://github.com/KryptonCaptain/Thaumic-Dyes/blob/master/src/main/java/thaumicdyes/common/lib/event/EventHandlerRunicLegacy.java#L190), which do things if you have 4 or more of a breach augment

Also, what would auto-repair even do, on armour that can't take damage? Which I've improved the code on slightly in dev, learning some stuff from TT ichor gear.

**Comment by Dayyer1** [comment]
Ah... yes... oops. Sorry about that.

**Comment by KryptonCaptain** [comment]
Closing because I believe the changes made to T3 set to be sufficient for now.

**Comment by Dayyer1** [comment]
The only problem I think about with the unenchantability of the armor is that I can't add the Last Stand enchantment. (From Openblocks, I think?)

https://www.spigotmc.org/threads/removing-enchantment-glow.196021/

"make enchantment instances yourself like fortune 3, add to the itemstack and listen on BlockBreakEvent to listen for what it does. Even if on enchantment event happens just remove enchantment and add in custom ones that do the exact same thing but you'll have to add in listeners."

"give it the data using color-codes in the lore (and end it with the reset color code). That'll work and the user won't see it."

^I just copy-pasted some stuff I noticed that might be helpful, which you can find again in the link.
